### ISSUE TITLE
Issue with the az.profile module

### ISSUE THREAD

**Issue by fopingn** [JamesDLD/AzureRm-PowerShell#1]
Hi,
I have an issue with the script. When running I have the following error message:

Info : Importing the Module Az.Profile with MinimumVersion 0.6.1  ... 
Generate_Log_Action : On action Importing the Module Az.Profile with MinimumVersion 0.6.1 : Le module «Az.Profile» de version «0.6.1» spécifié n’a pas été chargé, car aucun fichier 
de module valide n’a été trouvé dans un répertoire de module.
Au caractère C:\Users\foping\Desktop\AzurePowershell\remove recovery service vault from github.ps1:86 : 11
+ $Result = Generate_Log_Action -Action $Action -Command $Command -LogF ...
+           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Generate_Log_Action

I had already install the az module with the command:
import-module -name az

Do someone who have the same issue.

Thanks

**Comment by JamesDLD** [comment]
Hello,

could you please execute the following cmdlet and output the result here?
```
Import-Module Az.Profile

Get-Module
```

The output should display that you use a version higher than 0.6.1 for the module Az.Profile.
Sample output --> 
![image](https://user-images.githubusercontent.com/18073917/52062624-22fc4100-2571-11e9-8d55-ed4858d7cc03.png)

James

**Comment by JamesDLD** [comment]
Closing this issue.
Please consider upgrading to the last Az module version.
