### ISSUE TITLE
executed no results

### ISSUE THREAD

**Issue by porrascarlos802018** [JamesDLD/AzureRm-PowerShell#2]
I installed latest ad module
copied the contents of the script into a text file, renamed .ps1
executed and stays running without any output , after typing credentials.

**Comment by JamesDLD** [comment]
Could you add some screenshot please?

**Comment by porrascarlos802018** [comment]
![snapshot](https://user-images.githubusercontent.com/40796501/56501748-1ed72400-64cd-11e9-8f2f-b5420ede4ffc.JPG)

**Comment by JamesDLD** [comment]
Please show me a screenshot of your ps1 file.
Couldn't you just download the file from my github repo?
